
DROP TABLE TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE BALANCE CASCADE CONSTRAINTS;
DROP TABLE ACCOUNTPROPERTY CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE BALANCE (
    ACCNO INT,
    PRINCIPALAMOUNT NUMBER,
    PROFITAMOUNT NUMBER,
    CONSTRAINT PK_BALANCE PRIMARY KEY(ACCNO)
);

CREATE TABLE TRANSACTION (
    TID INT,
    ACCNO INT,
    AMOUNT NUMBER,
    TRANSACTIONCODE TIMESTAMP,
    CONSTRAINT PK_TRANSACTION PRIMARY KEY(TID)
);



CREATE TABLE ACCOUNTPROPERTY (
    ID INT,
    NAME VARCHAR2(50),
    PROFITRATE NUMBER,
    GRACEPERIOD INT,
    CONSTRAINT PK_ACCOUNTPROPERTY PRIMARY KEY(ID)
);

CREATE TABLE ACCOUNT (
    ID INT,
    NAME VARCHAR2(50),
    ACCCODE INT,
    OPENINGDATE TIMESTAMP,
    LASTDATEINTEREST TIMESTAMP,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY(ID)
);


-- Inserting values into BALANCE
INSERT INTO BALANCE (ACCNO, PRINCIPALAMOUNT, PROFITAMOUNT) VALUES (1, 1000, 50);
INSERT INTO BALANCE (ACCNO, PRINCIPALAMOUNT, PROFITAMOUNT) VALUES (2, 2000, 100);
INSERT INTO BALANCE (ACCNO, PRINCIPALAMOUNT, PROFITAMOUNT) VALUES (3, 1500, 75);
INSERT INTO BALANCE (ACCNO, PRINCIPALAMOUNT, PROFITAMOUNT) VALUES (4, 3000, 150);
INSERT INTO BALANCE (ACCNO, PRINCIPALAMOUNT, PROFITAMOUNT) VALUES (5, 2500, 125);

-- Inserting values into TRANSACTION
INSERT INTO TRANSACTION (TID, ACCNO, AMOUNT, TRANSACTIONCODE) VALUES (101, 1, 200, TO_TIMESTAMP('2023-01-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TRANSACTION (TID, ACCNO, AMOUNT, TRANSACTIONCODE) VALUES (102, 2, 150, TO_TIMESTAMP('2023-01-02 12:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TRANSACTION (TID, ACCNO, AMOUNT, TRANSACTIONCODE) VALUES (103, 3, 300, TO_TIMESTAMP('2023-01-03 15:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TRANSACTION (TID, ACCNO, AMOUNT, TRANSACTIONCODE) VALUES (104, 4, 250, TO_TIMESTAMP('2023-01-04 18:20:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TRANSACTION (TID, ACCNO, AMOUNT, TRANSACTIONCODE) VALUES (105, 5, 400, TO_TIMESTAMP('2023-01-05 20:10:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Inserting values into ACCOUNTPROPERTY
INSERT INTO ACCOUNTPROPERTY (ID, NAME, PROFITRATE, GRACEPERIOD) VALUES (1, 'Property 1', 0.05, 15);
INSERT INTO ACCOUNTPROPERTY (ID, NAME, PROFITRATE, GRACEPERIOD) VALUES (2, 'Property 2', 0.06, 20);
INSERT INTO ACCOUNTPROPERTY (ID, NAME, PROFITRATE, GRACEPERIOD) VALUES (3, 'Property 3', 0.04, 10);
INSERT INTO ACCOUNTPROPERTY (ID, NAME, PROFITRATE, GRACEPERIOD) VALUES (4, 'Property 4', 0.07, 25);
INSERT INTO ACCOUNTPROPERTY (ID, NAME, PROFITRATE, GRACEPERIOD) VALUES (5, 'Property 5', 0.08, 30);

-- Inserting values into ACCOUNT
INSERT INTO ACCOUNT (ID, NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST) VALUES (101, 'Account 1', 123, TO_TIMESTAMP('2023-01-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-01-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACCOUNT (ID, NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST) VALUES (102, 'Account 2', 456, TO_TIMESTAMP('2023-01-02 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-01-15 14:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACCOUNT (ID, NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST) VALUES (103, 'Account 3', 789, TO_TIMESTAMP('2023-01-03 13:45:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-01-20 16:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACCOUNT (ID, NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST) VALUES (104, 'Account 4', 101, TO_TIMESTAMP('2023-01-04 16:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-01-25 18:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACCOUNT (ID, NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST) VALUES (105, 'Account 5', 202, TO_TIMESTAMP('2023-01-05 18:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-01-30 20:20:00', 'YYYY-MM-DD HH24:MI:SS'));



--TASK 1
CREATE SEQUENCE ACCOUNT_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION GENERATE_ACCOUNT_ID(
    P_NAME VARCHAR2,
    P_ACC_CODE INT,
    P_OPENING_DATE DATE
) RETURN VARCHAR2 IS
    V_NAME_PREFIX VARCHAR2(3);
    V_SERIAL_NO NUMBER;
    V_ACCOUNT_ID VARCHAR2(50);
BEGIN
    V_NAME_PREFIX := UPPER(SUBSTR(P_NAME, 1, 3));
    SELECT ACCOUNT_ID_SEQ.NEXTVAL INTO V_SERIAL_NO FROM DUAL;
    V_ACCOUNT_ID := P_ACC_CODE || TO_CHAR(P_OPENING_DATE, 'YYYYMMDD') || '.' || V_NAME_PREFIX || '.' || LPAD(V_SERIAL_NO, 6, '0');
    RETURN V_ACCOUNT_ID;
END GENERATE_ACCOUNT_ID;
/

DECLARE
    V_NEW_ACCOUNT_ID VARCHAR2(50);
BEGIN
    V_NEW_ACCOUNT_ID := GENERATE_ACCOUNT_ID('JOHN DOE', 123, TO_DATE('20230101', 'YYYYMMDD'));
    DBMS_OUTPUT.PUT_LINE('GENERATED ACCOUNT_ID: ' || V_NEW_ACCOUNT_ID);
END;
/


--TASK 2

CREATE SEQUENCE ACCOUNT_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION GENERATE_ACCOUNT_ID(
    P_NAME VARCHAR2,
    P_ACC_CODE INT,
    P_OPENING_DATE TIMESTAMP
) RETURN VARCHAR2 IS
    V_NAME_PREFIX VARCHAR2(3);
    V_SERIAL_NO NUMBER;
    V_ACCOUNT_ID VARCHAR2(50);
BEGIN
    V_NAME_PREFIX := UPPER(SUBSTR(P_NAME, 1, 3));
    SELECT ACCOUNT_ID_SEQ.NEXTVAL INTO V_SERIAL_NO FROM DUAL;
    V_ACCOUNT_ID := P_ACC_CODE || TO_CHAR(P_OPENING_DATE, 'YYYYMMDD') || '.' || V_NAME_PREFIX || '.' || LPAD(V_SERIAL_NO, 6, '0');
    RETURN V_ACCOUNT_ID;
END GENERATE_ACCOUNT_ID;
/

SET LINESIZE 250;

DECLARE
    V_NEW_ACCOUNT_ID VARCHAR2(50);
BEGIN
    V_NEW_ACCOUNT_ID := GENERATE_ACCOUNT_ID('JOHN DOE', 123, TIMESTAMP '2023-01-01 12:00:00');
    INSERT INTO ACCOUNT (ACCOUNT_ID, NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST)
    VALUES (V_NEW_ACCOUNT_ID, 'JOHN DOE', 123, TIMESTAMP '2023-01-01 12:00:00', NULL);
    
    COMMIT;
END;
/

SELECT * FROM ACCOUNT;


--TASK 3
CREATE OR REPLACE TRIGGER BEFORE_INSERT_ACCOUNT
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
    :NEW.ACCOUNT_ID := GENERATE_ACCOUNT_ID(:NEW.NAME, :NEW.ACCCODE, :NEW.OPENINGDATE);
END;
/

INSERT INTO ACCOUNT (NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST)
VALUES ('JOHN DOE', 123, TIMESTAMP '2023-01-01 12:00:00', NULL);
SELECT * FROM ACCOUNT;


--TASK 4
CREATE OR REPLACE TRIGGER AFTER_INSERT_ACCOUNT_BALANCE
AFTER INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
    INSERT INTO BALANCE (ACCNO, PRINCIPALAMOUNT, PROFITAMOUNT)
    VALUES (:NEW.ACCOUNT_ID, 5000, 0);
END;
/

INSERT INTO ACCOUNT (NAME, ACCCODE, OPENINGDATE, LASTDATEINTEREST)
VALUES ('JOHN DOE', 123, TIMESTAMP '2023-01-01 12:00:00', NULL);
SELECT * FROM BALANCE;


--TASK 5
CREATE OR REPLACE TRIGGER AFTER_INSERT_TRANSACTION
AFTER INSERT ON TRANSACTION
FOR EACH ROW
BEGIN
    UPDATE BALANCE
    SET PRINCIPALAMOUNT = PRINCIPALAMOUNT + :NEW.AMOUNT
    WHERE ACCNO = :NEW.ACCNO;
END;
/

INSERT INTO TRANSACTION (TID, ACCNO, AMOUNT, TRANSACTIONCODE)
VALUES (1, '12320230101.JOH.000003', 1000, SYSTIMESTAMP);

SELECT * FROM BALANCE WHERE ACCNO = '12320230101.JOH.000003';

create or replace trigger UpdatePrincipalAmount
after insert on TRANSACTION
FOR EACH ROW
begin
    update Balance
    set PrincipalAmount = PrincipalAmount + :NEW.Amount
    WHERE ACCNO = :NEW.ACCNO;
END;
/
CREATE OR REPLACE TRIGGER ENTER_NEW_ENTRY
AFTER INSERT ON ACCOUNT
FOR EACH ROW 
BEGIN 
INSERT INTO BALANCE()