CREATE TABLE DOCTOR
(
    NAME VARCHAR2(20) NOT NULL,
    SPECIALIZATION CHAR(2) NOT NULL,
    FEE NUMBER,
    CONSTRAINT PK_DOCTOR PRIMARY KEY(NAME ,SPECIALIZATION)
);

CREATE TABLE PATIENT
(   
    PATIENT_NO CHAR(5) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(10),
    CONSTRAINT PK_PATIENT PRIMARY KEY(PATIENT_NO)
);
CREATE TABLE APPOINTMENT
(   
    PATIENT_NO CHAR(5) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    SPECIALIZATION CHAR(2) NOT NULL,
    CONSTRAINT PK_APPOINTMENTS PRIMARY KEY(PATIENT_NO , NAME , SPECIALIZATION)
);



ALTER TABLE APPOINTMENT ADD APPOINTMENT_DATE DATE;
ALTER TABLE APPOINTMENT DROP CONSTRAINT PK_APPOINTMENTS;
ALTER TABLE APPOINTMENT ADD CONSTRAINT PK_APPOINTMENTS PRIMARY KEY(APPOINTMENT_DATE , PATIENT_NO,NAME, SPECIALIZATION);
ALTER TABLE APPOINTMENT RENAME COLUMN PATIENT_NO TO P_NO;
ALTER TABLE APPOINTMENT RENAME COLUMN NAME TO D_NAME;
ALTER TABLE APPOINTMENT RENAME TO APPOINTMENT_INFO;
ALTER TABLE APPOINTMENT_INFO ADD CONSTRAINT FK_APPOINTMENT_DOCTOR FOREIGN KEY(D_NAME , SPECIALIZATION) REFERENCES DOCTOR(NAME,SPECIALIZATION);
ALTER TABLE APPOINTMENT_INFO ADD CONSTRAINT FK_APPOINTMENT_PATIENT FOREIGN KEY(P_NO) REFERENCES PATIENT(PATIENT_NO);

INSERT INTO DOCTOR VALUES('SAKEEF','CS',1600);
INSERT INTO DOCTOR VALUES('SHAHI','DS',500);
INSERT INTO DOCTOR VALUES('JUBAER','GS',100);
INSERT INTO DOCTOR VALUES('SHUFAN','CS',2343);


INSERT INTO PATIENT VALUES('02345','BARI','DHAKA');
INSERT INTO PATIENT VALUES('01345','SHUFAN','SIRAJGANJ');
INSERT INTO PATIENT VALUES('03345','NICOL','PABNA');
INSERT INTO PATIENT VALUES('04345','NICOLHAS','SHKHL');

INSERT INTO APPOINTMENT_INFO (APPOINTMENT_DATE, P_NO, D_NAME, SPECIALIZATION)
VALUES ('05-Jan-2012', '01345', 'SHUFAN', 'CS');
INSERT INTO APPOINTMENT_INFO (APPOINTMENT_DATE, P_NO, D_NAME, SPECIALIZATION)
VALUES('06-Jan-2012', '02345','SAKEEF','CS');
INSERT INTO APPOINTMENT_INFO (APPOINTMENT_DATE, P_NO, D_NAME, SPECIALIZATION)
VALUES('08-Jan-2012', '03345','JUBAER','GS');
INSERT INTO APPOINTMENT_INFO (APPOINTMENT_DATE, P_NO, D_NAME, SPECIALIZATION)
VALUES(SYSDATE, '04345','SHAHI','DS');



SELECT * FROM DOCTOR;
SELECT * FROM PATIENT;
SELECT * FROM APPOINTMENT_INFO;

SELECT NAME FROM DOCTOR WHERE FEE < 1500;
SELECT NAME FROM PATIENT WHERE ADDRESS LIKE '%KHL%';


SELECT * FROM PATIENT , APPOINTMENT_INFO;
SELECT * FROM PATIENT , APPOINTMENT_INFO WHERE PATIENT.PATIENT_NO = APPOINTMENT_INFO.P_NO;

SELECT P.NAME AS PATIENT_NAME, P.ADDRESS
FROM PATIENT P
INNER JOIN APPOINTMENT_INFO A ON P.PATIENT_NO = A.P_NO
WHERE TRUNC(A.APPOINTMENT_DATE) = TRUNC(SYSDATE);

SELECT D.NAME AS NAME , D.SPECIALIZATION , D.FEE
FROM DOCTOR D
INNER JOIN APPOINTMENT_INFO A ON D.NAME = A.D_NAME
INNER JOIN PATIENT P ON A.P_NO = P.PATIENT_NO
WHERE P.ADDRESS LIKE '%DHAKA%';


SELECT DISTINCT P.NAME AS PATIENT_NAME , P.PATIENT_NO, P.ADDRESS
FROM PATIENT P
INNER JOIN APPOINTMENT_INFO A ON P.PATIENT_NO = A.P_NO
INNER JOIN DOCTOR D ON A.D_NAME = D.NAME
WHERE D.SPECIALIZATION = 'GS' OR D.FEE > 1500;


UPDATE PATIENT
SET NAME = 'K', ADDRESS = 'RAJ'
WHERE PATIENT_NO = '01345';


DELETE FROM APPOINTMENT_INFO
WHERE P_NO = '02345';

DELETE FROM PATIENT
WHERE PATIENT_NO = '02345';



SELECT * FROM PATIENT;



DELETE FROM APPOINTMENT_INFO;
DELETE FROM DOCTOR;
DELETE FROM PATIENT;





DROP TABLE DOCTOR CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE APPOINTMENT_INFO CASCADE CONSTRAINTS;