DECLARE
        CURRENT_YEAR NUMBER := EXTRACT(YEAR FROM SYSDATE);
BEGIN
    IF MOD(CURRENT_YEAR,10) = 0 THEN
        DBMS_OUTPUT.PUT_LINE('YES');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO');
    END IF;
    DBMS_OUTPUT.PUT_LINE('Current Decade: '|| FLOOR(CURRENT_YEAR/10)*10);
END;
/

